# Generated by Django 2.2.28 on 2022-11-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresshwsaejmtjh'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresshwsaejmtjh',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
